config/routes.rb
Rails.application.routes.draw do
  resources :popular_gems, path: 'gems'
  put '/popular_gems/:id/like/:user_id', to: 'popular_gems#like', as: :like_gem
  put '/popular_gems/:id/unlike/:user_id', to: 'popular_gems#unlike', as: :unlike_gem
  root to: 'popular_gems#index'
  get '/downloads/', to: 'popular_gems#most_downloaded', as: :most_downloaded
  get '/active/', to: 'popular_gems#most_active', as: :most_active
  get '/hearts/', to: 'popular_gems#most_hearted', as: :most_hearted
  get '/popular_gems/:id/likes', to: 'popular_gems#likes', as: :gem_likes

  resources :comments
  post '/comments/:id/up_vote/:user_id', to: 'comments#up_vote', as: :up_vote_comment
  post '/comments/:id/down_vote/:user_id', to: 'comments#down_vote', as: :down_vote_comment

  resource :search

  resources :user
  get '/user/:id/comments', to: 'user#all_comments', as: :user_comments
  get '/user/:id/likes', to: 'user#all_likes', as: :user_likes

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  resources :stats, only: [:index]

  post '/receive_data', to: 'webhook#get_data'
end

app/views/shared/_gem_likes_label.html.erb
<% if gem.get_likes.size > 0 %>
  <%= link_to gem_likes_path(gem) do %>
    <span class="label label-success"><%= gem.get_likes.size %></span>
  <% end %>
<% end %>

app/views/shared/_heart_button.html.erb
<script>
  $(function() {
    return $("a[data-remote]").on("ajax:success", function(e, data, status, xhr) {
      var id, likes;
      id = "heart_" + data.gem.name;
      likes = data.likes;
      if (likes) {
        $("#" + id).removeClass("btn-default");
        $("#" + id).addClass("btn-danger");
      } else {
        $("#" + id).removeClass("btn-danger");
        $("#" + id).addClass("btn-default");
      }
    });
  });
</script>

<% if logged_in? %>
  <% if !(current_user.voted_up_on? gem) %>
    <% button = 'btn-default' %>
  <% else %>
    <% button = 'btn-danger' %>
  <% end %>
  <%= link_to like_gem_path(gem.id, current_user.id), method: :put, class: "btn #{button} btn-sm", id: "heart_#{gem.name}", remote: true do %>
    <span class="glyphicon glyphicon-heart"></span>
    <input type="hidden" value="<%= gem.id %>" name="popular_gem_id">
    <input type="hidden" value="<%= current_user.id %>" name="user_id">
  <% end %>
<% end %>

app/views/shared/_sidebar_table.html.erb
<div class="row">
  <div class="panel panel-default" id="<%= gem_id -%>">
    <div class="panel-heading">
      <h2 class="panel-title">
        <strong><%= title %></strong>
      </h2>
    </div>
    <div class="panel-body">
      <table class="table table-hover table-striped well">
        <tbody>
        <% gems.each do |gem| -%>
          <tr>
            <td>
              <%= link_to "#{gem.name}", gem %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>