config/routes.rb
Rails.application.routes.draw do
  resources :popular_gems, path: 'gems'
  put '/popular_gems/:id/like/:user_id', to: 'popular_gems#like', as: :like_gem
  put '/popular_gems/:id/unlike/:user_id', to: 'popular_gems#unlike', as: :unlike_gem
  root to: 'popular_gems#index'
  get '/downloads/', to: 'popular_gems#most_downloaded', as: :most_downloaded
  get '/active/', to: 'popular_gems#most_active', as: :most_active
  get '/hearts/', to: 'popular_gems#most_hearted', as: :most_hearted
  get '/popular_gems/:id/likes', to: 'popular_gems#likes', as: :gem_likes

  resources :comments
  post '/comments/:id/up_vote/:user_id', to: 'comments#up_vote', as: :up_vote_comment
  post '/comments/:id/down_vote/:user_id', to: 'comments#down_vote', as: :down_vote_comment

  resource :search

  resources :user
  get '/user/:id/comments', to: 'user#all_comments', as: :user_comments
  get '/user/:id/likes', to: 'user#all_likes', as: :user_likes

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  resources :stats, only: [:index]

  post '/receive_data', to: 'webhook#get_data'
end

app/models/popular_gem.rb
class PopularGem < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  extend FriendlyId
  friendly_id :name, use: :slugged
  acts_as_votable
  validates :name, uniqueness: true

  settings index: {number_of_shards: 1} do
    mappings dynamic: 'false' do
      indexes :name, analyzer: 'standard', index_options: 'offsets'
      indexes :description, analyzer: 'standard', index_options: 'offsets'
      indexes :total_downloads, type: 'long'
      indexes :gh_stars, type: 'long'
      indexes :gh_forks, type: 'long'
      indexes :gh_issues, type: 'long'
    end
  end

  class << self

    def search(query)
      __elasticsearch__.search(
        {
          from: 0,
          size: 50,
          query: {
            filtered: {
              query: {
                bool: {
                  should: [
                    {function_score: {
                      query: {
                        multi_match: {
                          query: query,
                          fields: ['name', 'description'],
                          type: "phrase"
                        }
                      },
                      functions: [
                        script_score: {
                          script: "_score * (doc['total_downloads'].value + doc['gh_stars'].value * 400  + doc['gh_forks'].value * 150 + doc['gh_issues'].value * 300) / 2**3.1"
                        }
                      ],
                      score_mode: "sum"
                    }}
                  ]
                }
              }
            }
          }
        }
      )
    end

    def top_downloaded(limit = nil)
      order(total_downloads: :desc).limit(limit)
    end

    def top_hearted(limit = nil)
      order(cached_votes_score: :desc).limit(limit)
    end

    def most_active(limit = nil)
      where("score > ?", 0).order(score: :desc).limit(limit)
    end

    def recently_liked(limit = nil)
      all.joins('inner join votes v on popular_gems.id = v.votable_id').where(v: {vote_flag: true, votable_type: 'PopularGem'}).group("popular_gems.id").order('max(v.updated_at) DESC').limit(limit)
    end

    def featured
      where(featured: true).order(updated_at: :desc)
    end

    def created_yesterday
      where("created_at >= ?", 1.day.ago).length
    end

    def updated_yesterday
      where("updated_at >= ? AND created_at < ?", 1.day.ago, 1.day.ago).length
    end

    def create_stat_logs
      CreatedStat.create(count: created_yesterday)
      UpdatedStat.create(count: updated_yesterday)
    end

  end

  def set_score

    score = ((gh_star_score(self.gh_stars.to_f)) + (gh_fork_score(self.gh_forks.to_f))
    +(self.cached_votes_up.to_f * 20.0) + (self.gh_issues.to_f * 5.5) +
      (total_downloads_score(self.total_downloads.to_f)))
    if self.gh_updated_at
      if recently_updated?(1)
        score*=1.5
      elsif recently_updated?(2)
        score*=1.25
      elsif recently_updated?(3)
        score*=1.15
      elsif recently_updated?(4)
        score*=1.1
      end
    end
    self.update(score: score)
  end

  def recently_updated?(week_number)
    if self.gh_updated_at
      self.gh_updated_at > week_number.week.ago && self.updated_at > week_number.week.ago
    else
      self.updated_at > week_number.week.ago
    end
  end

  private

  def gh_star_score(stars)
    case stars
      when stars > 10000
        score = stars*0.9
      when 3000..9999
        score = stars
      when 2000..2999
        score = stars * 1.1
      when 1000..1999
        score = stars *1.2
      when 700..999
        score = stars * 1.35
      when 500..699
        score = stars * 1.7
      when 300..499
        score = stars * 2
      else
        score = stars * 3
    end
    score
  end

  def gh_fork_score(forks)
    case forks
      when forks > 3000
        score = forks*0.9
      when 2000..2999
        score = forks
      when 1000..1999
        score = forks * 1.1
      when 500..999
        score = forks *1.5
      when 300..499
        score = forks * 2
      else
        score = forks * 3
    end
    score
  end

  def total_downloads_score(total_downloads)
    case total_downloads
      when total_downloads > 15000000
        score = total_downloads*0.01
      when 10000000..14999999
        score = total_downloads*0.02
      when 5000000..9999999
        score = total_downloads * 0.04
      when 2000000..4999999
        score = total_downloads *0.07
      when 1000000..1999999
        score = total_downloads * 0.1
      else
        score = total_downloads * 1
    end
    score
  end

end

app/controllers/popular_gems_controller.rb
class PopularGemsController < ApplicationController
  def index
    @recently_updated_gems = PopularGem.all.order(updated_at: :desc).pagination(params[:page])
    meta_tag_setter(
      'Ruby Gem discovery engine',
      'Discover the most downloaded and most loved Ruby Gems',
      'Ruby, gems, ruby gems, rails, top ruby gems, top rubygems,top rails gems, popular rubygems, popular ruby gems, popular gems, top gems, popular rails gems,list of top gems, list of top ruby gems, list of top rubygems, list of top rails gems',
      false
    )
  end

  def show
    @gem = PopularGem.friendly.find(params[:id])
    meta_tag_setter(
      "#{@gem.name}",
      "#{@gem.description}",
      "Ruby, gems, ruby gems, rails, #{@gem.name}, #{@gem.name} gem",
      true
    )
  end

  def edit
    gem = PopularGem.friendly.find(params[:id])
    PopularGem.without_timestamps do
      GemImporter.update_gem(gem.name)
    end
    updated_gem = PopularGem.friendly.find(params[:id])
    render json: {gem: updated_gem}
  end

  def most_downloaded
    @top_downloaded_gems = PopularGem.top_downloaded.pagination(params[:page])
    meta_tag_setter(
      'Most downloaded ruby gems',
      'Discover the most downloaded ruby gems',
      'Ruby, gems, ruby gems, rails',
      true
    )
  end

  def most_active
    @most_active_gems = PopularGem.most_active.pagination(params[:page])
    meta_tag_setter(
      'Most active ruby gems',
      'Discover the most active ruby gems',
      'Ruby, gems, ruby gems, rails',
      true
    )
  end

  def most_hearted
    @top_hearted_gems = PopularGem.top_hearted.pagination(params[:page])
    meta_tag_setter(
      'Most loved ruby gems',
      'Discover the most loved ruby gems',
      'Ruby, gems, ruby gems, rails',
      true
    )
  end

  def like
    gem = PopularGem.friendly.find(params[:id])

    PopularGem.without_timestamps do
      if current_user.liked?(gem)
        current_user.dislikes gem
        current_user.subtract_points(1)
      else
        current_user.likes gem
        current_user.add_points(1)
      end
    end

    render json: {gem: gem, likes: current_user.liked?(gem)}
  end

  def likes
    @gem = PopularGem.friendly.find(params[:id])
    @users = @gem.votes_for.up.by_type(User).voters
    meta_tag_setter(
      "#{@gem.name} likes",
      "Users that like #{@gem.name}",
      "Ruby, gems, ruby gems, rails, #{@gem.name}, #{@gem.name} gem",
      true
    )
  end

  private
  def gem_params
    params.require(:popular_gem).permit(:name)
  end
end

app/views/popular_gems/_gem_table.html.erb
<div class="col-xs-12">
  <div class="panel panel-info" id="<%= gem_id %>">
    <div class="panel-heading">
      <h2 class="panel-title"><strong><%= title %></strong>
        <% if view_more %>
          <small><%= link_to('View more', path_for_gems) %></small>
        <% end %>
      </h2>
    </div>
    <div class="panel-body">
      <% if use_pagination %>
        <div class="text-center"><%= paginate gems, :theme => 'twitter-bootstrap-3' %></div>
      <% end %>
      <table class="table table-hover table-striped">
        <thead>
        <tr>
          <% if logged_in? %>
            <th class="col-xs-1">
            </th>
          <% end %>
          <th class="col-xs-2">
            Gem name
          </th>
          <th class="col-xs-7">
            Description
          </th>
          <th class="col-xs-2">
            Total Downloads
          </th>
          <th class="col-xs-2">
            GitHub Stars
          </th>
        </tr>
        </thead>
        <tbody>
        <% gems.each do |gem| %>
          <tr>
            <% if logged_in? %>
              <td>
                <%= render partial: 'shared/heart_button', locals: {gem: gem} %>
              </td>
            <% end %>
            <td>
              <%= link_to "#{gem.name}", gem %>
            </td>
            <td>
              <%= truncate(gem.description, length: 200, separator: ' ') %>
            </td>
            <td>
              <%= number_with_delimiter(gem.total_downloads, :delimiter => ',') %>
            </td>
            <td>
              <%= number_with_delimiter(gem.gh_stars, :delimiter => ',') %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <% if use_pagination %>
        <div class="text-center"><%= paginate gems, :theme => 'twitter-bootstrap-3' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/popular_gems/index.html.erb
<div class="page-header blockquote-reverse col-md-11">
  <h1><span class="label label-info"><strong>discover new ruby gems</strong></span></h1>
</div>

<div class="">
  <%= render(partial: 'gem_table', locals: {
    gem_id: 'recently_updated_gems',
    path_for_gems: nil,
    gems: @recently_updated_gems,
    view_more: false,
    title: 'Recently updated gems',
    use_pagination: true})
  %>
</div>

app/views/popular_gems/likes.html.erb
<div class="">
  <div class="row">
    <div class="col-md-5 col-md-offset-3">
      <table class="table table-striped table-bordered table-hover well">
        <thead>
        <tr>
          <th>Users that like <%= @gem.name %></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><strong><%= link_to user.name, user %></strong></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/popular_gems/most_active.html.erb
  <%= render(partial: 'gem_table', locals: {
    gem_id: 'most_active',
    path_for_gems: nil,
    gems: @most_active_gems,
    view_more: false,
    title: 'Top gems',
    use_pagination: true})
  %>

app/views/popular_gems/most_downloaded.html.erb
<div class="">
  <%= render(partial: 'gem_table', locals: {
    gem_id: 'most_downloaded',
    path_for_gems: most_downloaded_path(page: 2),
    gems: @top_downloaded_gems,
    view_more: false,
    title: 'Most downloaded gems',
    use_pagination: true})
  %>
</div>

app/views/popular_gems/most_hearted.html.erb
<div class="">
  <%= render(partial: 'gem_table', locals: {
    gem_id: 'most_hearted',
    path_for_gems: most_hearted_path(page: 2),
    gems: @top_hearted_gems,
    view_more: false,
    title: 'Most loved gems',
    use_pagination: true})
  %>
</div>

app/views/popular_gems/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="well well-sm profile col-xs-12">
    <div class="col-xs-12">
      <%= render partial: 'shared/heart_button', locals: {gem: @gem} %>
      <%= render partial: 'shared/gem_likes_label', locals: {gem: @gem} %>
      <div class="col-md-4 col-xs-4 pull-right">
        <%= link_to 'Update Gem', edit_popular_gem_path(@gem), class: "btn btn-warning btn-block", id: "update_gem", remote: true %>
      </div>
      <h2 class="break-word"><%= @gem.name %></h2>

      <p><strong>Version: </strong><%= @gem.version %></p>

      <p class="break-word"><strong>About: </strong><%= @gem.description %></p>
    </div>

  </div>
  <div class="well-sm well col-xs-12">
    <h1>Install</h1>
    <h3>Terminal: <strong><span class="label label-primary"><%= "gem install #{@gem.name}" %></span></strong></h3>
    <h3>Gemfile: <strong><span class="label label-info"><%= "gem '#{@gem.name}', '~> #{@gem.version}'" %></span></strong></h3>
  </div>
  <div class="well well-sm profile col-xs-12">
    <div class="col-xs-8">
      <h2>Stats</h2>
    </div>
    <div class="col-xs-4">
      <h2>Links</h2>
    </div>
    <div class="col-xs-8">
      <table>
        <tr>
          <td class="col-xs-6">Total Downloads:</td>
          <td><strong><%= number_with_delimiter(@gem.total_downloads, :delimiter => ',') %></strong></td>
        </tr>
        <tr>
          <td class="col-xs-6">Version Downloads:</td>
          <td><strong><%= number_with_delimiter(@gem.version_downloads, :delimiter => ',') %></strong></td>
        </tr>
        <% if @gem.gh_updated_at != nil %>
          <tr>
            <td class="col-xs-6">Forks:</td>
            <td><strong><%= number_with_delimiter(@gem.gh_forks, :delimiter => ',') %></strong></td>
          </tr>
          <tr>
            <td class="col-xs-6">Stars:</td>
            <td><strong><%= number_with_delimiter(@gem.gh_stars, :delimiter => ',') %></strong></td>
          </tr>
          <tr>
            <td class="col-xs-6">Issues:</td>
            <td><strong><%= number_with_delimiter(@gem.gh_issues, :delimiter => ',') %></strong></td>
          </tr>
          <tr>
            <td class="col-xs-6">Last push:</td>
            <td>
              <strong><%= "#{@gem.gh_updated_at.year}-#{@gem.gh_updated_at.month}-#{@gem.gh_updated_at.day}" %></strong>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-xs-4">
      <a href="<%= @gem.url %>" class="btn btn-success col-xs-12">View on Rubygems</a>
      <br/>
      <br/>
      <a href="<%= @gem.project_url %>" class="btn btn-info col-xs-12">View Docs</a>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function () {
      $('#update_gem').click(function(){
        return $("a[data-remote]").on("ajax:success", function(e, data, status, xhr) {
          location.reload();
        })
      });
    })
  </script>
</div>