config/routes.rb
Rails.application.routes.draw do
  resources :popular_gems, path: 'gems'
  put '/popular_gems/:id/like/:user_id', to: 'popular_gems#like', as: :like_gem
  put '/popular_gems/:id/unlike/:user_id', to: 'popular_gems#unlike', as: :unlike_gem
  root to: 'popular_gems#index'
  get '/downloads/', to: 'popular_gems#most_downloaded', as: :most_downloaded
  get '/active/', to: 'popular_gems#most_active', as: :most_active
  get '/hearts/', to: 'popular_gems#most_hearted', as: :most_hearted
  get '/popular_gems/:id/likes', to: 'popular_gems#likes', as: :gem_likes

  resources :comments
  post '/comments/:id/up_vote/:user_id', to: 'comments#up_vote', as: :up_vote_comment
  post '/comments/:id/down_vote/:user_id', to: 'comments#down_vote', as: :down_vote_comment

  resource :search

  resources :user
  get '/user/:id/comments', to: 'user#all_comments', as: :user_comments
  get '/user/:id/likes', to: 'user#all_likes', as: :user_likes

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  resources :stats, only: [:index]

  post '/receive_data', to: 'webhook#get_data'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags :site => 'GemBundle' %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row clearfix">
    <div class="col-xs-12 column">
      <nav class="navbar navbar-default navbar" role="navigation" id="header">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" id="logo" href="/">GEMBUNDLE</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to('Top gems', most_active_path) %>
            </li>
            <li>
              <%= link_to('Stats', stats_path) %>
            </li>
            <li>
              <%= form_tag "/search", method: 'get', class: "navbar-form", role: "search" do %>
                <div class="form-group">
                  <%= text_field_tag 'gem_name', nil, class: "form-control", placeholder: 'Search for a gem' %>
                </div>
                <%= submit_tag :Search, class: "btn btn-default" %>
              <% end %>
            </li>
          </ul>
          <div class="">
            <ul class="nav navbar-nav navbar-right navbar-link">
              <% if logged_in? %>
                <li>
                  <%= link_to current_user, id: 'user_profile' do %>
                    <%= current_user.name %>
                    <span class="badge alert-info" id="points"><%= current_user.points %></span>
                  <% end %>
                </li>
                <li>
                  <%= link_to 'Sign out', :signout %>
                </li>
              <% else %>
                <li>
                  <%= link_to 'Sign in with Github', '/auth/github' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="clearfix" id="wrapper">
      <div class="col-xs-12">
        <div class="col-xs-10">
          <%= yield %>
        </div>
        <div class="col-xs-2 pull-right">
          <div>
            <%= render(partial: 'shared/sidebar_table', locals: {
              gem_id: 'recently_liked',
              gems: @recently_liked,
              title: 'Recent likes'})
            %>
          </div>
          <div>
            <%= render(partial: 'shared/sidebar_table', locals: {
              gem_id: 'recently_updated',
              gems: @recently_updated,
              title: 'Recent updates'})
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 row">
    <div class="text-center">
      <p class="muted">Created by
        <a href="https://twitter.com/stevepmag">@stevepmag</a></p>
    </div>
  </div>
</div>
</body>
</html>